In [1]:
import pandas as pd

In [8]:
file_path = "\\Users\\lguil\\OneDrive\\Documentos\\GitHub\\Movies-Data-Analysis\\Data\\imdb_top_1000.csv"

In [9]:
df = pd.read_csv(file_path)

In [14]:
df_2 = df.where(pd.notnull(df), None)

In [17]:
df_2.Genre.unique()

array(['Drama', 'Crime, Drama', 'Action, Crime, Drama',
       'Action, Adventure, Drama', 'Biography, Drama, History',
       'Action, Adventure, Sci-Fi', 'Drama, Romance', 'Western',
       'Action, Sci-Fi', 'Biography, Crime, Drama',
       'Action, Adventure, Fantasy', 'Comedy, Drama, Thriller',
       'Adventure, Drama, Sci-Fi', 'Animation, Adventure, Family',
       'Drama, War', 'Crime, Drama, Fantasy', 'Comedy, Drama, Romance',
       'Crime, Drama, Mystery', 'Crime, Drama, Thriller',
       'Action, Drama, Mystery', 'Drama, Family, Fantasy', 'Drama, Music',
       'Biography, Comedy, Drama', 'Drama, Mystery, Sci-Fi',
       'Biography, Drama, Music', 'Crime, Mystery, Thriller',
       'Animation, Adventure, Drama', 'Animation, Drama, War',
       'Adventure, Comedy, Sci-Fi', 'Horror, Mystery, Thriller',
       'Drama, Romance, War', 'Comedy, Drama, Family',
       'Animation, Drama, Fantasy', 'Action, Biography, Drama',
       'Animation, Action, Adventure', 'Drama, Western',
       'Action, Adventure', 'Comedy, Drama', 'Drama, Family',
       'Drama, Mystery, Thriller', 'Mystery, Thriller', 'Drama, Horror',
       'Drama, Mystery, War', 'Horror, Sci-Fi', 'Drama, Musical',
       'Comedy', 'Drama, Film-Noir', 'Comedy, Drama, War',
       'Drama, Thriller, War', 'Drama, Fantasy, Horror',
       'Crime, Drama, Music', 'Adventure, Drama, War',
       'Drama, Romance, Sci-Fi', 'Comedy, Romance', 'Comedy, Crime',
       'Drama, Family, Sport', 'Animation, Adventure, Comedy',
       'Adventure, Drama, Thriller', 'Comedy, Crime, Drama',
       'Crime, Drama, Sci-Fi', 'Adventure, Sci-Fi',
       'Adventure, Biography, Drama', 'Adventure, Mystery, Thriller',
       'Mystery, Romance, Thriller', 'Comedy, Musical, Romance',
       'Crime, Drama, Film-Noir', 'Drama, Mystery', 'Drama, Sci-Fi',
       'Action, Drama, War', 'Action, Drama', 'Adventure, Comedy, Drama',
       'Biography, Drama, Sport', 'Action, Comedy, Crime',
       'Action, Biography, Crime', 'Drama, Mystery, Romance',
       'Action, Drama, Sport', 'Drama, Fantasy, War',
       'Action, Drama, Sci-Fi', 'Biography, Drama',
       'Action, Comedy, Romance', 'Animation, Family, Fantasy',
       'Action, Thriller', 'Action, Adventure, Comedy',
       'Adventure, Comedy, Fantasy', 'Adventure, Drama, History',
       'Action, Drama, Thriller', 'Comedy, Music, Romance',
       'Drama, Fantasy, History', 'Crime, Thriller',
       'Adventure, Drama, Western', 'Comedy, War', 'Drama, Thriller',
       'Animation, Drama, Family', 'Drama, Romance, Thriller',
       'Comedy, Drama, Musical', 'Comedy, Drama, Fantasy',
       'Adventure, Comedy, Crime', 'Adventure, Drama, Fantasy',
       'Biography, Drama, Family', 'Animation, Comedy, Drama',
       'Drama, Sport', 'Animation, Action, Drama',
       'Adventure, Drama, Musical', 'Drama, Music, Romance',
       'Comedy, Crime, Romance', 'Comedy, Crime, Sport',
       'Drama, History, Romance', 'Adventure, Drama',
       'Animation, Adventure, Fantasy', 'Horror, Mystery, Sci-Fi',
       'Drama, Fantasy, Music', 'Action, Sci-Fi, Thriller',
       'Drama, Fantasy', 'Drama, Horror, Thriller', 'Drama, History',
       'Film-Noir, Mystery, Thriller', 'Fantasy, Horror, Mystery',
       'Action, Crime, Thriller', 'Comedy, Drama, Music',
       'Biography, Drama, Thriller', 'Animation, Biography, Drama',
       'Action, Mystery, Thriller', 'Crime, Drama, Romance',
       'Action, Adventure, Thriller', 'Crime, Drama, Musical',
       'Animation, Crime, Mystery', 'Action, Crime, Comedy',
       'Mystery, Sci-Fi, Thriller', 'Animation, Action, Crime',
       'Comedy, Fantasy, Romance', 'Drama, History, Thriller',
       'Animation, Action, Sci-Fi', 'Adventure, Family, Fantasy',
       'Drama, Fantasy, Romance', 'Drama, History, War',
       'Adventure, Thriller', 'Horror', 'Drama, Family, Musical',
       'Action, Drama, Western', 'Crime, Drama, Horror',
       'Drama, Film-Noir, Mystery', 'Comedy, Crime, Thriller',
       'Film-Noir, Mystery', 'Comedy, Crime, Mystery',
       'Drama, Fantasy, Mystery', 'Comedy, Horror',
       'Action, Adventure, History', 'Drama, Music, Mystery',
       'Comedy, Music', 'Comedy, Family', 'Drama, Music, Musical',
       'Action, Adventure, Horror', 'Action, Adventure, Biography',
       'Biography, Drama, War', 'Action, Adventure, Western',
       'Horror, Thriller', 'Comedy, Mystery, Romance',
       'Drama, Thriller, Western', 'Crime, Film-Noir, Thriller',
       'Drama, Film-Noir, Romance', 'Crime, Film-Noir, Mystery',
       'Action, Adventure, Romance', 'Comedy, Music, Musical',
       'Adventure, Horror, Sci-Fi', 'Fantasy, Horror',
       'Action, Drama, History', 'Adventure, Comedy, Family',
       'Animation, Biography, Crime', 'Adventure, Biography, Crime',
       'Adventure, Fantasy', 'Drama, History, Mystery',
       'Action, Comedy, Mystery', 'Adventure, Drama, Romance',
       'Drama, Sci-Fi, Thriller', 'Crime, Drama, History',
       'Action, Comedy, Fantasy', 'Family, Sci-Fi',
       'Adventure, History, War', 'Animation, Sci-Fi',
       'Family, Fantasy, Musical', 'Thriller', 'Comedy, Family, Fantasy',
       'Adventure, Comedy, Film-Noir', 'Film-Noir, Thriller',
       'Comedy, Family, Romance', 'Drama, Horror, Sci-Fi',
       'Comedy, Musical, War', 'Biography, Drama, Romance',
       'Drama, History, Music', 'Animation, Action, Fantasy',
       'Animation, Comedy, Fantasy', 'Comedy, Western',
       'Action, Adventure, War', 'Drama, Horror, Mystery',
       'Animation, Comedy, Crime', 'Action, Adventure, Crime',
       'Action, Adventure, Mystery', 'Action, Adventure, Family',
       'Action, Crime, Mystery', 'Animation, Drama, Romance',
       'Drama, War, Western', 'Adventure, Comedy, War'], dtype=object)

In [13]:
pd.notnull(df)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
996,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
997,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
998,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,False
999,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,False